AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 instance for React/Node.js app per environment

Parameters:
  Environment:
    Type: String
    AllowedValues: [dev, staging, uat, prod]
    Description: Deployment environment

  InstanceType:
    Type: String
    Default: t3.micro
    AllowedValues:
      - t2.micro
      - t3.micro
      - t3.small
      - t3.medium
    Description: EC2 instance type

  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair to SSH into the instance

  VPCId:
    Type: AWS::EC2::VPC::Id
    Description: VPC to launch the instance into

  SubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: Subnet to launch the instance into

  SecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Security group with HTTP/HTTPS/SSH access

Resources:
  AppEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      SubnetId: !Ref SubnetId
      SecurityGroupIds:
        - !Ref SecurityGroupId
      ImageId: ami-0c02fb55956c7d316 # Amazon Linux 2 (change based on region or use SSM)
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-app-server"
        - Key: Environment
          Value: !Ref Environment
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          curl -sL https://rpm.nodesource.com/setup_18.x | bash -
          yum install -y nodejs git
          cd /home/ec2-user
          git clone https://github.com/your-org/your-repo.git
          cd your-repo
          npm install
          npm run build
          npm start

Outputs:
  InstanceId:
    Description: EC2 Instance ID
    Value: !Ref AppEC2Instance

  PublicIP:
    Description: Public IP of the instance
    Value: !GetAtt AppEC2Instance.PublicIp
