AWSTemplateFormatVersion: '2010-09-09'
Description: Master template for creating EC2, S3, RDS, Lambda, CloudFront, and Route53 resources.

Resources:
  S3Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: http://localhost:4566/hosted-bucket/s3.yaml

  EC2Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: http://localhost:4566/hosted-bucket/ec2.yaml

  RDSStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: http://localhost:4566/hosted-bucket/rds-postgres.yaml

  LambdaStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: http://localhost:4566/hosted-bucket/lambda.yaml

  CloudFrontStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: http://localhost:4566/hosted-bucket/cloudfront.yaml

  Route53Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: http://localhost:4566/hosted-bucket/route53.yaml
