AWSTemplateFormatVersion: '2010-09-09'
Description: S3 buckets for React frontend hosting in multiple environments.

Parameters:
  ProjectName:
    Type: String
    Default: myproject
    Description: Name of the project to prefix bucket names.

Resources:
  S3BucketDev:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${ProjectName}-frontend-dev"
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      AccessControl: PublicRead

  S3BucketStaging:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${ProjectName}-frontend-staging"
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      AccessControl: PublicRead

  S3BucketUAT:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${ProjectName}-frontend-uat"
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      AccessControl: PublicRead

  S3BucketProd:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${ProjectName}-frontend-prod"
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      AccessControl: PublicRead

Outputs:
  DevBucket:
    Description: Dev environment bucket name
    Value: !Ref S3BucketDev

  ProdBucket:
    Description: Prod environment bucket name
    Value: !Ref S3BucketProd