trigger:
  branches:
    include:
      - main  # Trigger on pushes to 'main' branch

pool:
  vmImage: 'ubuntu-latest'  # Use Microsoft-hosted Ubuntu agent

variables:
  AWS_REGION: 'us-east-1'                  # Your AWS region
  S3_BUCKET_NAME: 'your-s3-bucket-name'     # Your S3 bucket name
  CLOUDFRONT_DISTRIBUTION_ID: 'your-distribution-id'  # CloudFront Distribution ID

stages:
  - stage: Install
    displayName: 'Install Dependencies'
    jobs:
      - job: InstallJob
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'    # Specify Node.js version
            displayName: 'Install Node.js'

          - script: |
              npm install
            displayName: 'Install npm packages'

  - stage: Build
    displayName: 'Build Project'
    dependsOn: Install
    jobs:
      - job: BuildJob
        steps:
          - script: |
              npm run build
            displayName: 'Build npm project'

  - stage: Test
    displayName: 'Run Tests'
    dependsOn: Build
    jobs:
      - job: TestJob
        steps:
          - script: |
              npm test
            displayName: 'Run npm tests'

  - stage: Deploy
    displayName: 'Upload to S3 and Invalidate CloudFront'
    dependsOn: Test
    jobs:
      - job: DeployJob
        steps:
          - task: AwsCli@1
            inputs:
              awsCredentials: 'aws-service-connection'  # Name of the Azure DevOps AWS service connection (or you can pass keys manually)
              regionName: '$(AWS_REGION)'
              command: 's3'
              arguments: 'sync build/ s3://$(S3_BUCKET_NAME) --delete'
            displayName: 'Upload build folder to S3'

          - task: AwsCli@1
            inputs:
              awsCredentials: 'aws-service-connection'
              regionName: '$(AWS_REGION)'
              command: 'cloudfront'
              arguments: 'create-invalidation --distribution-id $(CLOUDFRONT_DISTRIBUTION_ID) --paths "/*"'
            displayName: 'Invalidate CloudFront Cache'
